
/// 内置词库数据（不依赖网络）
class BuiltInWordBooks {
  /// 获取内置词库列表
  static List<Map<String, dynamic>> getWordBooks() {
    return [
      {
        'name': 'CET-4 词汇',
        'description': '大学英语四级核心词汇',
        'wordCount': 25,
        'words': _cet4Words,
      },
      {
        'name': 'CET-6 词汇',
        'description': '大学英语六级核心词汇',
        'wordCount': 25,
        'words': _cet6Words,
      },
      {
        'name': '考研英语词汇',
        'description': '考研英语大纲核心词汇',
        'wordCount': 25,
        'words': _kaoyanWords,
      },
      {
        'name': '高考英语词汇',
        'description': '高考英语必背词汇',
        'wordCount': 25,
        'words': _gaokaoWords,
      },
      {
        'name': '雅思核心词汇',
        'description': '雅思考试核心词汇',
        'wordCount': 25,
        'words': _ieltsWords,
      },
      {
        'name': '托福核心词汇',
        'description': '托福考试核心词汇',
        'wordCount': 25,
        'words': _toeflWords,
      },
      {
        'name': '日常口语 1000 词',
        'description': '日常交流必备基础词汇',
        'wordCount': 25,
        'words': _dailyWords,
      },
      {
        'name': 'GRE 核心词汇',
        'description': 'GRE 考试核心词汇',
        'wordCount': 25,
        'words': _greWords,
      },
    ];
  }

  /// CET-4 词汇
  static const List<Map<String, String>> _cet4Words = [
    {'word': 'abandon', 'phonetic': '/əˈbændən/', 'definition': 'v. 放弃，遗弃'},
    {'word': 'ability', 'phonetic': '/əˈbɪləti/', 'definition': 'n. 能力，才能'},
    {'word': 'able', 'phonetic': '/ˈeɪbl/', 'definition': 'adj. 能够的，有能力的'},
    {'word': 'about', 'phonetic': '/əˈbaʊt/', 'definition': 'prep. 关于，大约'},
    {'word': 'above', 'phonetic': '/əˈbʌv/', 'definition': 'prep. 在...之上'},
    {'word': 'abroad', 'phonetic': '/əˈbrɔːd/', 'definition': 'adv. 在国外，到国外'},
    {'word': 'absence', 'phonetic': '/ˈæbsəns/', 'definition': 'n. 缺席，缺乏'},
    {'word': 'absolute', 'phonetic': '/ˈæbsəluːt/', 'definition': 'adj. 绝对的，完全的'},
    {'word': 'accept', 'phonetic': '/əkˈsept/', 'definition': 'v. 接受，认可'},
    {'word': 'accident', 'phonetic': '/ˈæksɪdənt/', 'definition': 'n. 事故，意外'},
    {'word': 'account', 'phonetic': '/əˈkaʊnt/', 'definition': 'n. 账户，描述'},
    {'word': 'achieve', 'phonetic': '/əˈtʃiːv/', 'definition': 'v. 完成，达到'},
    {'word': 'across', 'phonetic': '/əˈkrɒs/', 'definition': 'prep. 横穿，穿过'},
    {'word': 'action', 'phonetic': '/ˈækʃn/', 'definition': 'n. 行动，动作'},
    {'word': 'active', 'phonetic': '/ˈæktɪv/', 'definition': 'adj. 积极的，主动的'},
    {'word': 'activity', 'phonetic': '/ækˈtɪvəti/', 'definition': 'n. 活动，行动'},
    {'word': 'actual', 'phonetic': '/ˈæktʃuəl/', 'definition': 'adj. 实际的，真实的'},
    {'word': 'adapt', 'phonetic': '/əˈdæpt/', 'definition': 'v. 适应，改编'},
    {'word': 'add', 'phonetic': '/æd/', 'definition': 'v. 增加，添加'},
    {'word': 'address', 'phonetic': '/əˈdres/', 'definition': 'n. 地址 v. 解决'},
    {'word': 'adequate', 'phonetic': '/ˈædɪkwət/', 'definition': 'adj. 足够的，适当的'},
    {'word': 'adjust', 'phonetic': '/əˈdʒʌst/', 'definition': 'v. 调整，适应'},
    {'word': 'administration', 'phonetic': '/ədˌmɪnɪˈstreɪʃn/', 'definition': 'n. 管理，行政'},
    {'word': 'admire', 'phonetic': '/ədˈmaɪər/', 'definition': 'v. 钦佩，欣赏'},
    {'word': 'admit', 'phonetic': '/ədˈmɪt/', 'definition': 'v. 承认，允许进入'},
  ];

  /// CET-6 词汇
  static const List<Map<String, String>> _cet6Words = [
    {'word': 'abundant', 'phonetic': '/əˈbʌndənt/', 'definition': 'adj. 丰富的，充裕的'},
    {'word': 'academic', 'phonetic': '/ˌækəˈdemɪk/', 'definition': 'adj. 学术的'},
    {'word': 'access', 'phonetic': '/ˈækses/', 'definition': 'n. 入口 v. 访问'},
    {'word': 'accomplish', 'phonetic': '/əˈkʌmplɪʃ/', 'definition': 'v. 完成，实现'},
    {'word': 'accurate', 'phonetic': '/ˈækjərət/', 'definition': 'adj. 准确的'},
    {'word': 'achieve', 'phonetic': '/əˈtʃiːv/', 'definition': 'v. 完成，达到'},
    {'word': 'acquire', 'phonetic': '/əˈkwaɪər/', 'definition': 'v. 获得，取得'},
    {'word': 'adequate', 'phonetic': '/ˈædɪkwət/', 'definition': 'adj. 足够的'},
    {'word': 'adjust', 'phonetic': '/əˈdʒʌst/', 'definition': 'v. 调整，适应'},
    {'word': 'administration', 'phonetic': '/ədˌmɪnɪˈstreɪʃn/', 'definition': 'n. 管理，行政'},
    {'word': 'advance', 'phonetic': '/ədˈvæns/', 'definition': 'v. 前进 n. 进步'},
    {'word': 'advocate', 'phonetic': '/ˈædvəkeɪt/', 'definition': 'v. 提倡 n. 倡导者'},
    {'word': 'affect', 'phonetic': '/əˈfekt/', 'definition': 'v. 影响'},
    {'word': 'afford', 'phonetic': '/əˈfɔːrd/', 'definition': 'v. 负担得起'},
    {'word': 'agenda', 'phonetic': '/əˈdʒendə/', 'definition': 'n. 议程，日程'},
    {'word': 'aggregate', 'phonetic': '/ˈæɡrɪɡət/', 'definition': 'v. 聚集 n. 总计'},
    {'word': 'alternative', 'phonetic': '/ɔːlˈtɜːrnətɪv/', 'definition': 'n. 替代品 adj. 替代的'},
    {'word': 'ambiguous', 'phonetic': '/æmˈbɪɡjuəs/', 'definition': 'adj. 模糊的'},
    {'word': 'amend', 'phonetic': '/əˈmend/', 'definition': 'v. 修改，修正'},
    {'word': 'analyze', 'phonetic': '/ˈænəlaɪz/', 'definition': 'v. 分析'},
    {'word': 'annual', 'phonetic': '/ˈænjuəl/', 'definition': 'adj. 年度的'},
    {'word': 'anticipate', 'phonetic': '/ænˈtɪsɪpeɪt/', 'definition': 'v. 预期，期望'},
    {'word': 'apparent', 'phonetic': '/əˈpærənt/', 'definition': 'adj. 明显的'},
    {'word': 'appreciate', 'phonetic': '/əˈpriːʃieɪt/', 'definition': 'v. 欣赏，感激'},
    {'word': 'approach', 'phonetic': '/əˈproʊtʃ/', 'definition': 'n. 方法 v. 接近'},
  ];

  /// 考研英语词汇
  static const List<Map<String, String>> _kaoyanWords = [
    {'word': 'abandon', 'phonetic': '/əˈbændən/', 'definition': 'v. 放弃'},
    {'word': 'abide', 'phonetic': '/əˈbaɪd/', 'definition': 'v. 遵守，坚持'},
    {'word': 'abolish', 'phonetic': '/əˈbɒlɪʃ/', 'definition': 'v. 废除'},
    {'word': 'absolute', 'phonetic': '/ˈæbsəluːt/', 'definition': 'adj. 绝对的'},
    {'word': 'absorb', 'phonetic': '/əbˈzɔːrb/', 'definition': 'v. 吸收'},
    {'word': 'abstract', 'phonetic': '/ˈæbstrækt/', 'definition': 'adj. 抽象的 n. 摘要'},
    {'word': 'abundant', 'phonetic': '/əˈbʌndənt/', 'definition': 'adj. 丰富的'},
    {'word': 'accelerate', 'phonetic': '/əkˈseləreɪt/', 'definition': 'v. 加速'},
    {'word': 'accept', 'phonetic': '/əkˈsept/', 'definition': 'v. 接受'},
    {'word': 'access', 'phonetic': '/ˈækses/', 'definition': 'n. 入口 v. 访问'},
    {'word': 'accident', 'phonetic': '/ˈæksɪdənt/', 'definition': 'n. 事故'},
    {'word': 'accompany', 'phonetic': '/əˈkʌmpəni/', 'definition': 'v. 陪伴'},
    {'word': 'accomplish', 'phonetic': '/əˈkʌmplɪʃ/', 'definition': 'v. 完成'},
    {'word': 'accord', 'phonetic': '/əˈkɔːrd/', 'definition': 'v. 符合 n. 协议'},
    {'word': 'account', 'phonetic': '/əˈkaʊnt/', 'definition': 'n. 账户'},
    {'word': 'accumulate', 'phonetic': '/əˈkjuːmjəleɪt/', 'definition': 'v. 积累'},
    {'word': 'accurate', 'phonetic': '/ˈækjərət/', 'definition': 'adj. 准确的'},
    {'word': 'achieve', 'phonetic': '/əˈtʃiːv/', 'definition': 'v. 完成'},
    {'word': 'acknowledge', 'phonetic': '/əkˈnɒlɪdʒ/', 'definition': 'v. 承认'},
    {'word': 'acquire', 'phonetic': '/əˈkwaɪər/', 'definition': 'v. 获得'},
    {'word': 'adapt', 'phonetic': '/əˈdæpt/', 'definition': 'v. 适应'},
    {'word': 'adequate', 'phonetic': '/ˈædɪkwət/', 'definition': 'adj. 足够的'},
    {'word': 'adjust', 'phonetic': '/əˈdʒʌst/', 'definition': 'v. 调整'},
    {'word': 'administer', 'phonetic': '/ədˈmɪnɪstər/', 'definition': 'v. 管理'},
    {'word': 'adolescent', 'phonetic': '/ˌædəˈlesnt/', 'definition': 'n. 青少年'},
  ];

  /// 高考英语词汇
  static const List<Map<String, String>> _gaokaoWords = [
    {'word': 'abandon', 'phonetic': '/əˈbændən/', 'definition': 'v. 放弃'},
    {'word': 'ability', 'phonetic': '/əˈbɪləti/', 'definition': 'n. 能力'},
    {'word': 'able', 'phonetic': '/ˈeɪbl/', 'definition': 'adj. 能够的'},
    {'word': 'about', 'phonetic': '/əˈbaʊt/', 'definition': 'prep. 关于'},
    {'word': 'above', 'phonetic': '/əˈbʌv/', 'definition': 'prep. 在...之上'},
    {'word': 'abroad', 'phonetic': '/əˈbrɔːd/', 'definition': 'adv. 在国外'},
    {'word': 'accept', 'phonetic': '/əkˈsept/', 'definition': 'v. 接受'},
    {'word': 'accident', 'phonetic': '/ˈæksɪdənt/', 'definition': 'n. 事故'},
    {'word': 'account', 'phonetic': '/əˈkaʊnt/', 'definition': 'n. 账户'},
    {'word': 'achieve', 'phonetic': '/əˈtʃiːv/', 'definition': 'v. 完成'},
    {'word': 'across', 'phonetic': '/əˈkrɒs/', 'definition': 'prep. 穿过'},
    {'word': 'action', 'phonetic': '/ˈækʃn/', 'definition': 'n. 行动'},
    {'word': 'active', 'phonetic': '/ˈæktɪv/', 'definition': 'adj. 积极的'},
    {'word': 'activity', 'phonetic': '/ækˈtɪvəti/', 'definition': 'n. 活动'},
    {'word': 'actual', 'phonetic': '/ˈæktʃuəl/', 'definition': 'adj. 实际的'},
    {'word': 'adapt', 'phonetic': '/əˈdæpt/', 'definition': 'v. 适应'},
    {'word': 'add', 'phonetic': '/æd/', 'definition': 'v. 增加'},
    {'word': 'address', 'phonetic': '/əˈdres/', 'definition': 'n. 地址'},
    {'word': 'admire', 'phonetic': '/ədˈmaɪər/', 'definition': 'v. 钦佩'},
    {'word': 'admit', 'phonetic': '/ədˈmɪt/', 'definition': 'v. 承认'},
    {'word': 'advance', 'phonetic': '/ədˈvæns/', 'definition': 'v. 前进'},
    {'word': 'advice', 'phonetic': '/ədˈvaɪs/', 'definition': 'n. 建议'},
    {'word': 'advise', 'phonetic': '/ədˈvaɪz/', 'definition': 'v. 建议'},
    {'word': 'affair', 'phonetic': '/əˈfer/', 'definition': 'n. 事件'},
    {'word': 'affect', 'phonetic': '/əˈfekt/', 'definition': 'v. 影响'},
  ];

  /// 雅思词汇
  static const List<Map<String, String>> _ieltsWords = [
    {'word': 'abandon', 'phonetic': '/əˈbændən/', 'definition': 'v. 放弃'},
    {'word': 'abundant', 'phonetic': '/əˈbʌndənt/', 'definition': 'adj. 丰富的'},
    {'word': 'academic', 'phonetic': '/ˌækəˈdemɪk/', 'definition': 'adj. 学术的'},
    {'word': 'access', 'phonetic': '/ˈækses/', 'definition': 'n. 入口 v. 访问'},
    {'word': 'accommodate', 'phonetic': '/əˈkɒmədeɪt/', 'definition': 'v. 容纳'},
    {'word': 'accompany', 'phonetic': '/əˈkʌmpəni/', 'definition': 'v. 陪伴'},
    {'word': 'accomplish', 'phonetic': '/əˈkʌmplɪʃ/', 'definition': 'v. 完成'},
    {'word': 'accord', 'phonetic': '/əˈkɔːrd/', 'definition': 'n. 协议'},
    {'word': 'accurate', 'phonetic': '/ˈækjərət/', 'definition': 'adj. 准确的'},
    {'word': 'achieve', 'phonetic': '/əˈtʃiːv/', 'definition': 'v. 完成'},
    {'word': 'acknowledge', 'phonetic': '/əkˈnɒlɪdʒ/', 'definition': 'v. 承认'},
    {'word': 'acquire', 'phonetic': '/əˈkwaɪər/', 'definition': 'v. 获得'},
    {'word': 'adapt', 'phonetic': '/əˈdæpt/', 'definition': 'v. 适应'},
    {'word': 'adequate', 'phonetic': '/ˈædɪkwət/', 'definition': 'adj. 足够的'},
    {'word': 'adjust', 'phonetic': '/əˈdʒʌst/', 'definition': 'v. 调整'},
    {'word': 'administration', 'phonetic': '/ədˌmɪnɪˈstreɪʃn/', 'definition': 'n. 管理'},
    {'word': 'advance', 'phonetic': '/ədˈvæns/', 'definition': 'v. 前进'},
    {'word': 'advocate', 'phonetic': '/ˈædvəkeɪt/', 'definition': 'v. 提倡'},
    {'word': 'affect', 'phonetic': '/əˈfekt/', 'definition': 'v. 影响'},
    {'word': 'afford', 'phonetic': '/əˈfɔːrd/', 'definition': 'v. 负担得起'},
    {'word': 'agenda', 'phonetic': '/əˈdʒendə/', 'definition': 'n. 议程'},
    {'word': 'aggregate', 'phonetic': '/ˈæɡrɪɡət/', 'definition': 'v. 聚集'},
    {'word': 'aim', 'phonetic': '/eɪm/', 'definition': 'n. 目标 v. 瞄准'},
    {'word': 'albeit', 'phonetic': '/ɔːlˈbiːɪt/', 'definition': 'conj. 虽然'},
    {'word': 'allocate', 'phonetic': '/ˈæləkeɪt/', 'definition': 'v. 分配'},
  ];

  /// 托福词汇
  static const List<Map<String, String>> _toeflWords = [
    {'word': 'abandon', 'phonetic': '/əˈbændən/', 'definition': 'v. 放弃'},
    {'word': 'abdomen', 'phonetic': '/ˈæbdəmən/', 'definition': 'n. 腹部'},
    {'word': 'aberrant', 'phonetic': '/æˈberənt/', 'definition': 'adj. 异常的'},
    {'word': 'abide', 'phonetic': '/əˈbaɪd/', 'definition': 'v. 遵守'},
    {'word': 'aboard', 'phonetic': '/əˈbɔːrd/', 'definition': 'adv. 在船上'},
    {'word': 'abolish', 'phonetic': '/əˈbɒlɪʃ/', 'definition': 'v. 废除'},
    {'word': 'abrupt', 'phonetic': '/əˈbrʌpt/', 'definition': 'adj. 突然的'},
    {'word': 'abscess', 'phonetic': '/ˈæbses/', 'definition': 'n. 脓肿'},
    {'word': 'absence', 'phonetic': '/ˈæbsəns/', 'definition': 'n. 缺席'},
    {'word': 'absolute', 'phonetic': '/ˈæbsəluːt/', 'definition': 'adj. 绝对的'},
    {'word': 'absorb', 'phonetic': '/əbˈzɔːrb/', 'definition': 'v. 吸收'},
    {'word': 'abstract', 'phonetic': '/ˈæbstrækt/', 'definition': 'adj. 抽象的'},
    {'word': 'absurd', 'phonetic': '/əbˈsɜːrd/', 'definition': 'adj. 荒谬的'},
    {'word': 'abundant', 'phonetic': '/əˈbʌndənt/', 'definition': 'adj. 丰富的'},
    {'word': 'academic', 'phonetic': '/ˌækəˈdemɪk/', 'definition': 'adj. 学术的'},
    {'word': 'accelerate', 'phonetic': '/əkˈseləreɪt/', 'definition': 'v. 加速'},
    {'word': 'accent', 'phonetic': '/ˈæksent/', 'definition': 'n. 口音'},
    {'word': 'access', 'phonetic': '/ˈækses/', 'definition': 'n. 入口'},
    {'word': 'accessible', 'phonetic': '/əkˈsesəbl/', 'definition': 'adj. 可进入的'},
    {'word': 'accident', 'phonetic': '/ˈæksɪdənt/', 'definition': 'n. 事故'},
    {'word': 'acclaim', 'phonetic': '/əˈkleɪm/', 'definition': 'v. 欢呼'},
    {'word': 'accommodate', 'phonetic': '/əˈkɒmədeɪt/', 'definition': 'v. 容纳'},
    {'word': 'accompany', 'phonetic': '/əˈkʌmpəni/', 'definition': 'v. 陪伴'},
    {'word': 'accomplish', 'phonetic': '/əˈkʌmplɪʃ/', 'definition': 'v. 完成'},
    {'word': 'accord', 'phonetic': '/əˈkɔːrd/', 'definition': 'n. 协议'},
  ];

  /// 日常口语词汇
  static const List<Map<String, String>> _dailyWords = [
    {'word': 'hello', 'phonetic': '/həˈloʊ/', 'definition': 'int. 你好'},
    {'word': 'hi', 'phonetic': '/haɪ/', 'definition': 'int. 嗨'},
    {'word': 'goodbye', 'phonetic': '/ɡʊdˈbaɪ/', 'definition': 'int. 再见'},
    {'word': 'bye', 'phonetic': '/baɪ/', 'definition': 'int. 再见'},
    {'word': 'thanks', 'phonetic': '/θæŋks/', 'definition': 'int. 谢谢'},
    {'word': 'thank you', 'phonetic': '/θæŋk juː/', 'definition': '谢谢你'},
    {'word': 'please', 'phonetic': '/pliːz/', 'definition': 'adv. 请'},
    {'word': 'sorry', 'phonetic': '/ˈsɒri/', 'definition': 'adj. 抱歉的'},
    {'word': 'excuse me', 'phonetic': '/ɪkˈskjuːz miː/', 'definition': '劳驾'},
    {'word': 'yes', 'phonetic': '/jes/', 'definition': 'adv. 是的'},
    {'word': 'no', 'phonetic': '/noʊ/', 'definition': 'adv. 不'},
    {'word': 'okay', 'phonetic': '/oʊˈkeɪ/', 'definition': 'adj. 好的'},
    {'word': 'great', 'phonetic': '/ɡreɪt/', 'definition': 'adj. 伟大的'},
    {'word': 'good', 'phonetic': '/ɡʊd/', 'definition': 'adj. 好的'},
    {'word': 'bad', 'phonetic': '/bæd/', 'definition': 'adj. 坏的'},
    {'word': 'happy', 'phonetic': '/ˈhæpi/', 'definition': 'adj. 快乐的'},
    {'word': 'sad', 'phonetic': '/sæd/', 'definition': 'adj. 悲伤的'},
    {'word': 'tired', 'phonetic': '/ˈtaɪərd/', 'definition': 'adj. 疲倦的'},
    {'word': 'hungry', 'phonetic': '/ˈhʌŋɡri/', 'definition': 'adj. 饥饿的'},
    {'word': 'thirsty', 'phonetic': '/ˈθɜːrsti/', 'definition': 'adj. 口渴的'},
    {'word': 'water', 'phonetic': '/ˈwɔːtər/', 'definition': 'n. 水'},
    {'word': 'food', 'phonetic': '/fuːd/', 'definition': 'n. 食物'},
    {'word': 'coffee', 'phonetic': '/ˈkɒfi/', 'definition': 'n. 咖啡'},
    {'word': 'tea', 'phonetic': '/tiː/', 'definition': 'n. 茶'},
    {'word': 'milk', 'phonetic': '/mɪlk/', 'definition': 'n. 牛奶'},
  ];

  /// GRE 词汇
  static const List<Map<String, String>> _greWords = [
    {'word': 'aberrant', 'phonetic': '/æˈberənt/', 'definition': 'adj. 异常的'},
    {'word': 'abeyance', 'phonetic': '/əˈbeɪəns/', 'definition': 'n. 中止'},
    {'word': 'abjure', 'phonetic': '/əbˈdʒʊr/', 'definition': 'v. 放弃'},
    {'word': 'abnegate', 'phonetic': '/ˈæbnɪɡeɪt/', 'definition': 'v. 放弃'},
    {'word': 'abominable', 'phonetic': '/əˈbɒmɪnəbl/', 'definition': 'adj. 可恶的'},
    {'word': 'aboriginal', 'phonetic': '/ˌæbəˈrɪdʒɪnl/', 'definition': 'adj. 原始的'},
    {'word': 'abortive', 'phonetic': '/əˈbɔːrtɪv/', 'definition': 'adj. 失败的'},
    {'word': 'abrade', 'phonetic': '/əˈbreɪd/', 'definition': 'v. 磨损'},
    {'word': 'abrogate', 'phonetic': '/ˈæbrəɡeɪt/', 'definition': 'v. 废除'},
    {'word': 'abscond', 'phonetic': '/əbˈskɒnd/', 'definition': 'v. 潜逃'},
    {'word': 'absolution', 'phonetic': '/ˌæbsəˈluːʃn/', 'definition': 'n. 赦免'},
    {'word': 'abstemious', 'phonetic': '/æbˈstiːmiəs/', 'definition': 'adj. 节制的'},
    {'word': 'abstruse', 'phonetic': '/æbˈstruːs/', 'definition': 'adj. 深奥的'},
    {'word': 'accolade', 'phonetic': '/ˈækəleɪd/', 'definition': 'n. 荣誉'},
    {'word': 'acrimony', 'phonetic': '/ˈækrɪmoʊni/', 'definition': 'n. 刻薄'},
    {'word': 'admonish', 'phonetic': '/ədˈmɒnɪʃ/', 'definition': 'v. 警告'},
    {'word': 'aesthetic', 'phonetic': '/esˈθetɪk/', 'definition': 'adj. 审美的'},
    {'word': 'affable', 'phonetic': '/ˈæfəbl/', 'definition': 'adj. 和蔼的'},
    {'word': 'aggrandize', 'phonetic': '/əˈɡrændaɪz/', 'definition': 'v. 扩大'},
    {'word': 'alacrity', 'phonetic': '/əˈlækrəti/', 'definition': 'n. 敏捷'},
    {'word': 'amalgamate', 'phonetic': '/əˈmælɡəmeɪt/', 'definition': 'v. 混合'},
    {'word': 'ambivalent', 'phonetic': '/æmˈbɪvələnt/', 'definition': 'adj. 矛盾的'},
    {'word': 'ameliorate', 'phonetic': '/əˈmiːliəreɪt/', 'definition': 'v. 改善'},
    {'word': 'anachronism', 'phonetic': '/əˈnækrənɪzəm/', 'definition': 'n. 时代错误'},
    {'word': 'anathema', 'phonetic': '/əˈnæθəmə/', 'definition': 'n. 诅咒'},
  ];
}